### ISSUE TITLE
Research Spike: Terminal input for customizing protein display

### ISSUE THREAD

**Issue by smcintosh881** [moltimate/moltimate-frontend#10]

**Comment by smcintosh881** [comment]
@blackpan2 @jmiller656  @steplica  so this can totally be done. I think this would be cool to work on for second release, since motif maker wont be that intensive since the road work for it is already laid out.

**Comment by blackpan2** [comment]
Moving it to release two is fine with me. I will update this as I add the board for release two this weekend.
