### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by smcintosh881** [moltimate/moltimate-frontend#2]
Size Estimation: S

Add ESLint to the frontend repo using the Airbnb rules.

Acceptance Criteria:
- ESLint is set up for the repository

**Comment by blackpan2** [comment]
Can we make ESLint a check for PRs so that we have a secondary confirmation before we merge something?

**Comment by smcintosh881** [comment]
I like enforcing it as part of the commit/push process. That way no bad styling gets into commits. Its strict but you can override if need be with a -f
