### ISSUE TITLE
Add the ability to provide the IP Address of the Backend

### ISSUE THREAD

**Issue by blackpan2** [moltimate/moltimate-frontend#24]
We should be able to provide the IP & Port of the backend to the frontend at run time so that each of them can be run on independent instances while they are deployed.

**Comment by smcintosh881** [comment]
@blackpan2 
Im a little confused. Is this for Dev environment set up?

**Comment by steplica** [comment]
@blackpan2 We will deploy the frontend and backend on the same GCP project, as separate services in the app engine

**Comment by blackpan2** [comment]
Closed due to being managed by GCP
