### ISSUE TITLE
Mock Backend Request

### ISSUE THREAD

**Issue by smcintosh881** [moltimate/moltimate-frontend#4]
Size Estimation: S

Make a simple get request of the backend in order to get dummy data back.

Acceptance Criteria:
- A request can be made of the backend while running both on a local machine

**Comment by smcintosh881** [comment]
@steplica @jmiller656 let me know when services is ready to try and hit

**Comment by blackpan2** [comment]
We should be able to hit `/debug` and get dummy data back which should be enough for the completion of this.
