### ISSUE TITLE
Configure the CI to run during PRs (Frontend)

### ISSUE THREAD

**Issue by blackpan2** [moltimate/moltimate-frontend#6]
BLOCKED BY: #5 
Size Estimation: S

Configure PRs so that they are required to pass the tests in the repo before they can be merged.

Acceptance Criteria:
- CI is configured to run project tests
- PRs are blocked for code that fails tests

**Comment by smcintosh881** [comment]
Include in this setting up a dependency Bot: [Dependabot](https://github.com/marketplace/dependabot) or [Greenkeeper](https://github.com/marketplace/greenkeeper)

**Comment by smcintosh881** [comment]
Auto Security Audit Tool [snyk](https://github.com/marketplace/snyk)

**Comment by blackpan2** [comment]
Updated size estimation to S

**Comment by blackpan2** [comment]
Dependabot supports Java as well as Javascript so, in theory, we could use it in the backend. @steplica what are you're thoughts?

**Comment by blackpan2** [comment]
#5 Closed unblocking
