### ISSUE TITLE
Setup UI testing framework

### ISSUE THREAD

**Issue by blackpan2** [moltimate/moltimate-frontend#7]
Size Estimation: _

Setup UI testing for the project using Selenium.

Acceptance Criteria:
- UI Testing implemented
- Simple UI test added

**Comment by smcintosh881** [comment]
@blackpan2 There are some interesting behaviors with how litemol lays in the dom tree, so I'd like to propose we make this a lower priority, especially for R1. I've got unit tests set up, but I think E2E is out of scope for now.

**Comment by blackpan2** [comment]
Alright, I would be fine with delaying this until we are later on in the project. It is something that we should be aware of, as you mentioned there might be additional complexity in regards to interacting with their component.
