### ISSUE TITLE
Research Spike: Find how to have image of protein 

### ISSUE THREAD

**Issue by smcintosh881** [moltimate/moltimate-frontend#9]

**Comment by smcintosh881** [comment]
@blackpan2 so NGL viewer has screen shot and image download options, but its like png/jpg file types. Im not sure it provides the image quality sponsors want. We talked about being able to export the pdb info so they can bring it into chimra to make images that way. They should be able to do that so Im going to close this.

**Comment by blackpan2** [comment]
Now that we have a better idea of how the motif file works in relation to a full PDB file (by selecting some of the atoms from it and then hiding the rest). We should be able to take the items in the viewer and then export the resulting PDB file which could then be opened in Chimera for a higher quality image to be taken.
